# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_zxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zxx', models.CharField(max_length=30, verbose_name='名字')),
                ('email_zxx', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('phone_zxx', models.CharField(max_length=30, verbose_name='手机')),
                ('comments_zxx', models.TextField(verbose_name='评论')),
            ],
            options={
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
            },
        ),
    ]
